### ISSUE TITLE
Suggestion to add post to the "Web analytics" page

### ISSUE THREAD

**Issue by coleifer** [makaimc/fullstackpython.github.com#51]
I wrote a blog post about building a self-hosted Google analytics clone using Python and Flask:

http://charlesleifer.com/blog/saturday-morning-hacks-building-an-analytics-app-with-flask/

If you think it would be helpful, I'd like to suggest including it in the "Web analytics" page under the *Web analytics resources* heading.

Thanks for your excellent and informative site!

**Comment by makaimc** [comment]
Hey Charles, yea I definitely remember the great walkthrough you did on that post. I actually have it linked to on the [Flask page](http://www.fullstackpython.com/flask.html) but it's kind of lost in the middle of that big list of resources. I'm planning to rearrange that list anyway since it's a bit unwieldy. I think moving your post to the web analytics post makes sense.

**Comment by makaimc** [comment]
Okay, I created a new section on the [web analytics](http://www.fullstackpython/web-analytics.html) page for Python-specific analytics resources and moved your tutorial to there. I think that'll work better, but take a look and let me know.

I'm also going to create a Python ORMs page for Peewee, SQLAlchemy, the Django ORM and other projects & resources. If you've got good ones saved up, it'd be a huge help to dump them into a GitHub issue ticket or pull request.

Will you be at PyCon US next month?

**Comment by coleifer** [comment]
Hey I didn't realize it was already linked from the Flask page, but yes moving to the Analytics page might be helpful. Unfortunately, no, I won't be there but I certainly wish I was.
